"""Generate 5 figures for the ML chemistry narrative report.

Figure 1: epsilon_k vs n_fluorine scatter with ±1σ uncertainty band
Figure 2: VP vs Henry's screening funnel with binomial CI error bars
Figure 3: Henry's sensitivity to epsilon_ij with horizontal error bars
Figure 4: Uncertainty envelope with per-tree + k_ij combined CIs
Figure 5: Pareto frontier with vertical H_ratio uncertainty bars
"""

import logging
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from rdkit import Chem

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

from model.uncertainty import binomial_ci


def classify_molecule(smiles: str) -> str:
    """Classify as HFO (F, no Cl), HCFO (F and Cl), or Cl-olefin (Cl, no F)."""
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        return "unknown"

    n_f = sum(1 for atom in mol.GetAtoms() if atom.GetAtomicNum() == 9)
    n_cl = sum(1 for atom in mol.GetAtoms() if atom.GetAtomicNum() == 17)

    if n_f > 0 and n_cl == 0:
        return "HFO"
    elif n_f > 0 and n_cl > 0:
        return "HCFO"
    elif n_cl > 0 and n_f == 0:
        return "Cl-olefin"
    return "other"

REPO_ROOT = Path(__file__).parent.parent
SAVED_DIR = REPO_ROOT / "model" / "saved"
FIG_DIR = REPO_ROOT / "figures" / "23_ml_chemistry_narrative"

# Reference values (cyclopentane)
CYCLOPENTANE = {"m": 2.3655, "sigma": 3.7114, "epsilon_k": 288.84}

# Acceptance band for Henry's ratio
H_RATIO_MIN = 0.5
H_RATIO_MAX = 2.0


def load_data():
    """Load all required datasets."""
    logger.info("Loading datasets...")

    # Full candidate set with all metadata
    full_df = pd.read_csv(SAVED_DIR / "novel_pcsaft_predictions.csv")

    # VP-passing candidates with Henry's data
    henrys_df = pd.read_csv(SAVED_DIR / "henrys_constant_screening.csv")

    # Standout candidates with credibility analysis
    standout_df = pd.read_csv(SAVED_DIR / "standout_candidates_credibility.csv")

    # Propagated uncertainty (generated by scripts/propagate_uncertainty.py)
    uq_path = SAVED_DIR / "uncertainty_propagated.csv"
    uq_df = None
    if uq_path.exists():
        uq_df = pd.read_csv(uq_path)
        logger.info(f"Loaded {len(uq_df)} rows with propagated uncertainty")
    else:
        logger.warning(
            "uncertainty_propagated.csv not found; figures will use fallback "
            "uncertainty. Run: python scripts/propagate_uncertainty.py"
        )

    logger.info(f"Loaded {len(full_df)} total candidates")
    logger.info(f"Loaded {len(henrys_df)} VP-passing candidates with Henry's data")
    logger.info(f"Loaded {len(standout_df)} standout candidates")

    return full_df, henrys_df, standout_df, uq_df


def figure1_epsilon_k_vs_fluorines(full_df):
    """Figure 1: Scatter of epsilon_k vs n_fluorine with ±1σ uncertainty band."""
    logger.info("Generating Figure 1: epsilon_k vs n_fluorine...")

    fig, ax = plt.subplots(figsize=(10, 6))

    class_colors = {
        "HFO": "#1f77b4",
        "HCFO": "#ff7f0e",
        "Cl-olefin": "#2ca02c",
        "other": "#d62728",
    }

    for mol_class in ["HFO", "HCFO", "Cl-olefin"]:
        subset = full_df[full_df["molecule_class"] == mol_class]
        ax.scatter(
            subset["n_fluorine"],
            subset["epsilon_k"],
            c=class_colors[mol_class],
            label=mol_class,
            alpha=0.6,
            s=20,
        )

    # ±1σ uncertainty band: mean ± mean_std per fluorine count
    if "std_epsilon_k" in full_df.columns:
        grouped = full_df.groupby("n_fluorine").agg(
            eps_mean=("epsilon_k", "mean"),
            eps_std_mean=("std_epsilon_k", "mean"),
        ).reset_index()
        grouped = grouped.sort_values("n_fluorine")

        ax.fill_between(
            grouped["n_fluorine"],
            grouped["eps_mean"] - grouped["eps_std_mean"],
            grouped["eps_mean"] + grouped["eps_std_mean"],
            alpha=0.15, color="gray", label="Mean ± 1σ (RF tree std)",
        )

    ax.axhline(
        CYCLOPENTANE["epsilon_k"],
        color="black",
        linestyle="--",
        linewidth=1.5,
        label="Cyclopentane (ε/k = 288.84 K)",
    )

    hfos = full_df[full_df["molecule_class"] == "HFO"]
    if len(hfos) > 0:
        top_hfo = hfos.nlargest(1, "epsilon_k").iloc[0]
        ax.annotate(
            top_hfo["smiles"],
            xy=(top_hfo["n_fluorine"], top_hfo["epsilon_k"]),
            xytext=(10, 10),
            textcoords="offset points",
            fontsize=9,
            bbox=dict(boxstyle="round,pad=0.3", facecolor="yellow", alpha=0.5),
            arrowprops=dict(arrowstyle="->", connectionstyle="arc3,rad=0"),
        )

    ax.set_xlabel("Number of Fluorine Atoms", fontsize=14)
    ax.set_ylabel("ε/k (K)", fontsize=14)
    ax.set_title("Predicted Dispersion Energy vs Fluorination Level", fontsize=16)
    ax.legend(fontsize=11)
    ax.grid(alpha=0.3)
    ax.tick_params(labelsize=12)

    plt.tight_layout()
    fig.savefig(FIG_DIR / "epsilon_k_vs_fluorines.png", dpi=300)
    plt.close(fig)
    logger.info("Saved Figure 1: epsilon_k_vs_fluorines.png")


def figure2_vp_vs_henrys_funnel(full_df, henrys_df):
    """Figure 2: Two-panel with histogram and funnel + binomial CI bars."""
    logger.info("Generating Figure 2: VP vs Henry's screening funnel...")

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))

    # Left panel: Henry's ratio histogram (log scale)
    h_ratios = henrys_df["H_ratio"].dropna()
    ax1.hist(h_ratios, bins=50, alpha=0.7, color="steelblue", edgecolor="black")
    ax1.axvspan(H_RATIO_MIN, H_RATIO_MAX, alpha=0.2, color="green", label="Acceptance Region")
    ax1.set_xlabel("H / H(cyclopentane)", fontsize=14)
    ax1.set_ylabel("Count", fontsize=14)
    ax1.set_title("Henry's Constant Distribution\n(VP-Passing Candidates)", fontsize=16)
    ax1.set_xscale("log")
    ax1.legend(fontsize=11)
    ax1.grid(alpha=0.3)
    ax1.tick_params(labelsize=12)

    # Right panel: Screening funnel with binomial CI error bars
    total_candidates = len(full_df)
    vp_passing = len(henrys_df)
    henry_passing = henrys_df[
        (henrys_df["H_ratio"] >= H_RATIO_MIN)
        & (henrys_df["H_ratio"] <= H_RATIO_MAX)
    ]
    n_henry_passing = len(henry_passing)

    stages = ["Total\nEnumerated", "VP-Passing\n(298K)", "Henry-Screened\n[0.5, 2.0]"]
    counts = [total_candidates, vp_passing, n_henry_passing]
    bar_colors = ["#d62728", "#ff7f0e", "#2ca02c"]

    # Binomial CIs on pass rates (VP and Henry's as fraction of total)
    ci_vp = binomial_ci(vp_passing, total_candidates)
    ci_h = binomial_ci(n_henry_passing, vp_passing)
    yerr_lo = [0, counts[1] - ci_vp["ci_lo"] * total_candidates,
               counts[2] - ci_h["ci_lo"] * vp_passing]
    yerr_hi = [0, ci_vp["ci_hi"] * total_candidates - counts[1],
               ci_h["ci_hi"] * vp_passing - counts[2]]
    yerr = [np.maximum(yerr_lo, 0), np.maximum(yerr_hi, 0)]

    bars = ax2.bar(stages, counts, color=bar_colors, alpha=0.7, edgecolor="black",
                   yerr=yerr, capsize=5, error_kw={"ecolor": "black", "elinewidth": 1.5})
    ax2.set_ylabel("Number of Candidates", fontsize=14)
    ax2.set_title("Screening Funnel (error bars: 95% binomial CI)", fontsize=15)
    ax2.tick_params(labelsize=12)
    ax2.grid(axis="y", alpha=0.3)

    for bar, count in zip(bars, counts):
        height = bar.get_height()
        ax2.text(
            bar.get_x() + bar.get_width() / 2,
            height + max(yerr_hi) * 0.3 if max(yerr_hi) > 0 else height,
            f"{count}",
            ha="center",
            va="bottom",
            fontsize=12,
            fontweight="bold",
        )

    plt.tight_layout()
    fig.savefig(FIG_DIR / "vp_vs_henrys_comparison.png", dpi=300)
    plt.close(fig)
    logger.info("Saved Figure 2: vp_vs_henrys_comparison.png")


def figure3_henrys_sensitivity(standout_df):
    """Figure 3: H ratio vs epsilon_ij with horizontal uncertainty bars."""
    logger.info("Generating Figure 3: Henry's sensitivity analysis...")

    fig, ax = plt.subplots(figsize=(10, 6))

    epsilon_hexane = 323.0
    epsilon_cyclopentane = CYCLOPENTANE["epsilon_k"]

    standout_df = standout_df.copy()
    standout_df["epsilon_ij"] = np.sqrt(standout_df["epsilon_k"] * epsilon_hexane)
    standout_df["epsilon_ij_ref"] = np.sqrt(epsilon_cyclopentane * epsilon_hexane)
    standout_df["epsilon_ij_ratio"] = standout_df["epsilon_ij"] / standout_df["epsilon_ij_ref"]

    # Horizontal error bars from tree variance on epsilon_k
    xerr = None
    if "epsilon_k_tree_std" in standout_df.columns:
        eps_std = standout_df["epsilon_k_tree_std"].fillna(0).values
        # Propagate: d(eps_ij)/d(eps_k) = 0.5 * sqrt(eps_hexane / eps_k)
        d_ij = 0.5 * np.sqrt(epsilon_hexane / standout_df["epsilon_k"].values) * eps_std
        xerr = d_ij / standout_df["epsilon_ij_ref"].values

    ax.errorbar(
        standout_df["epsilon_ij_ratio"],
        standout_df["H_ratio"],
        xerr=xerr,
        fmt="o",
        alpha=0.6,
        markersize=5,
        color="steelblue",
        ecolor="gray",
        elinewidth=0.8,
        capsize=2,
        label="Candidates (±1σ ε_ij)",
    )

    # Theoretical Boltzmann curve
    epsilon_ij_ratios = np.linspace(0.7, 1.1, 100)
    kT = 298
    epsilon_ij_ref = standout_df["epsilon_ij_ref"].iloc[0]
    theoretical_H = np.exp(epsilon_ij_ref * (epsilon_ij_ratios - 1) / kT)

    ax.plot(
        epsilon_ij_ratios,
        theoretical_H,
        color="red",
        linestyle="--",
        linewidth=2,
        label="Theoretical Boltzmann (exp[ε_ij/kT])",
    )

    ax.axhspan(H_RATIO_MIN, H_RATIO_MAX, alpha=0.2, color="green", label="Acceptance Region")

    ax.set_xlabel("ε_ij / ε_ij(ref)", fontsize=14)
    ax.set_ylabel("H / H(cyclopentane)", fontsize=14)
    ax.set_title("Henry's Constant Sensitivity to Interaction Energy", fontsize=16)
    ax.set_yscale("log")
    ax.legend(fontsize=11)
    ax.grid(alpha=0.3)
    ax.tick_params(labelsize=12)

    plt.tight_layout()
    fig.savefig(FIG_DIR / "henrys_sensitivity.png", dpi=300)
    plt.close(fig)
    logger.info("Saved Figure 3: henrys_sensitivity.png")


def figure4_uncertainty_envelope(standout_df, uq_df=None):
    """Figure 4: H ratio with per-tree + k_ij combined 95% CIs."""
    logger.info("Generating Figure 4: Uncertainty envelope for standout candidates...")

    # Merge propagated uncertainty if available
    if uq_df is not None and "H_ratio_lo" in uq_df.columns:
        merged = standout_df.merge(
            uq_df[["smiles", "H_ratio_lo", "H_ratio_hi",
                    "H_ratio_tree_lo", "H_ratio_tree_hi",
                    "H_ratio_tree_mean"]],
            on="smiles",
            how="left",
            suffixes=("", "_uq"),
        )
        has_propagated = "H_ratio_lo" in merged.columns and merged["H_ratio_lo"].notna().any()
    else:
        merged = standout_df.copy()
        has_propagated = False

    merged = merged.sort_values("H_ratio").reset_index(drop=True)
    plot_df = merged.head(20)

    fig, ax = plt.subplots(figsize=(12, 6))
    x_pos = np.arange(len(plot_df))

    if has_propagated and plot_df["H_ratio_lo"].notna().any():
        # Combined CI (tree + k_ij)
        h_center = plot_df["H_ratio"].values
        y_err_lower = np.abs(h_center - plot_df["H_ratio_lo"].values)
        y_err_upper = np.abs(plot_df["H_ratio_hi"].values - h_center)
        yerr_combined = [np.nan_to_num(y_err_lower), np.nan_to_num(y_err_upper)]

        ax.errorbar(
            x_pos - 0.15, h_center, yerr=yerr_combined,
            fmt="s", markersize=6, color="#d62728", ecolor="#d62728",
            capsize=4, alpha=0.7, label="95% CI (tree + k_ij)",
        )

        # Tree-only CI
        if plot_df["H_ratio_tree_lo"].notna().any():
            y_err_lo_tree = np.abs(h_center - plot_df["H_ratio_tree_lo"].values)
            y_err_hi_tree = np.abs(plot_df["H_ratio_tree_hi"].values - h_center)
            yerr_tree = [np.nan_to_num(y_err_lo_tree), np.nan_to_num(y_err_hi_tree)]

            ax.errorbar(
                x_pos + 0.15, h_center, yerr=yerr_tree,
                fmt="o", markersize=6, color="steelblue", ecolor="steelblue",
                capsize=4, alpha=0.7, label="95% CI (tree-only, k_ij=0)",
            )
    else:
        # Fallback: use epsilon sensitivity from standout_credibility
        H_ref = 51676.0
        if "H_eps_plus" in plot_df.columns and "H_eps_minus" in plot_df.columns:
            H_ratio_plus = plot_df["H_eps_plus"] / H_ref
            H_ratio_minus = plot_df["H_eps_minus"] / H_ref
            y_err_upper = np.abs(H_ratio_plus - plot_df["H_ratio"])
            y_err_lower = np.abs(plot_df["H_ratio"] - H_ratio_minus)
            yerr = [y_err_lower.values, y_err_upper.values]
        else:
            yerr = None

        ax.errorbar(
            x_pos, plot_df["H_ratio"], yerr=yerr,
            fmt="o", markersize=6, color="steelblue", ecolor="gray",
            capsize=4, alpha=0.7, label="ε sensitivity (fallback)",
        )

    ax.axhspan(H_RATIO_MIN, H_RATIO_MAX, alpha=0.2, color="green", label="Acceptance Region")

    ax.set_xlabel("Candidate Index (sorted by H ratio)", fontsize=14)
    ax.set_ylabel("H / H(cyclopentane)", fontsize=14)
    title = "Top 20 Candidates with Propagated 95% CIs" if has_propagated else \
            "Top 20 Candidates with Uncertainty from ε Sensitivity"
    ax.set_title(title, fontsize=16)
    ax.set_xticks(x_pos[::2])
    ax.set_xticklabels(x_pos[::2])
    ax.legend(fontsize=10, loc="upper left")
    ax.grid(alpha=0.3)
    ax.tick_params(labelsize=12)

    plt.tight_layout()
    fig.savefig(FIG_DIR / "uncertainty_envelope.png", dpi=300)
    plt.close(fig)
    logger.info("Saved Figure 4: uncertainty_envelope.png")


def figure5_pareto_frontier(henrys_df, uq_df=None):
    """Figure 5: Pareto frontier with vertical H_ratio uncertainty bars."""
    logger.info("Generating Figure 5: Pareto frontier...")

    henrys_df = henrys_df.copy()
    henrys_df["h_deviation"] = np.abs(henrys_df["H_ratio"] - 1.0)
    henrys_df["molecule_class"] = henrys_df["smiles"].apply(classify_molecule)

    # Merge propagated uncertainty for error bars
    if uq_df is not None and "H_ratio_tree_lo" in uq_df.columns:
        henrys_df = henrys_df.merge(
            uq_df[["smiles", "H_ratio_tree_lo", "H_ratio_tree_hi"]],
            on="smiles", how="left",
        )
        henrys_df["h_dev_lo"] = np.abs(henrys_df["H_ratio_tree_lo"] - 1.0)
        henrys_df["h_dev_hi"] = np.abs(henrys_df["H_ratio_tree_hi"] - 1.0)
        has_uq = True
    else:
        has_uq = False

    fig, ax = plt.subplots(figsize=(10, 6))

    class_colors = {
        "HFO": "#1f77b4",
        "HCFO": "#ff7f0e",
        "Cl-olefin": "#2ca02c",
        "other": "#d62728",
    }

    for mol_class in ["HFO", "HCFO", "Cl-olefin"]:
        subset = henrys_df[henrys_df["molecule_class"] == mol_class]
        if len(subset) > 0:
            n_f_list = []
            for smi in subset["smiles"]:
                mol = Chem.MolFromSmiles(smi)
                n_f = sum(1 for atom in mol.GetAtoms() if atom.GetAtomicNum() == 9) if mol else 0
                n_f_list.append(n_f)
            subset = subset.copy()
            subset["n_fluorine"] = n_f_list

            if has_uq and subset["h_dev_lo"].notna().any():
                yerr_lo = np.abs(subset["h_deviation"] - subset["h_dev_lo"]).values
                yerr_hi = np.abs(subset["h_dev_hi"] - subset["h_deviation"]).values
                yerr = [np.nan_to_num(yerr_lo, nan=0), np.nan_to_num(yerr_hi, nan=0)]
                ax.errorbar(
                    subset["n_fluorine"], subset["h_deviation"],
                    yerr=yerr, fmt="o",
                    color=class_colors[mol_class], ecolor=class_colors[mol_class],
                    label=mol_class, alpha=0.5, markersize=4, elinewidth=0.3,
                    capsize=0,
                )
            else:
                ax.scatter(
                    subset["n_fluorine"],
                    subset["h_deviation"],
                    c=class_colors[mol_class],
                    label=mol_class,
                    alpha=0.6,
                    s=30,
                )

    ax.set_xlabel("Number of Fluorine Atoms", fontsize=14)
    ax.set_ylabel("|H / H(ref) - 1|", fontsize=14)
    title_suffix = " (with 95% tree-CI bars)" if has_uq else ""
    ax.set_title(f"Pareto Frontier: Solubility Match vs Fluorination{title_suffix}", fontsize=15)
    ax.set_yscale("log")
    ax.legend(fontsize=11)
    ax.grid(alpha=0.3)
    ax.tick_params(labelsize=12)

    ax.text(
        0.95, 0.05, "Pareto-optimal\n(lower-right)",
        transform=ax.transAxes, fontsize=11, ha="right", va="bottom",
        bbox=dict(boxstyle="round,pad=0.5", facecolor="yellow", alpha=0.5),
    )

    plt.tight_layout()
    fig.savefig(FIG_DIR / "pareto_frontier.png", dpi=300)
    plt.close(fig)
    logger.info("Saved Figure 5: pareto_frontier.png")


def main():
    full_df, henrys_df, standout_df, uq_df = load_data()

    figure1_epsilon_k_vs_fluorines(full_df)
    figure2_vp_vs_henrys_funnel(full_df, henrys_df)
    figure3_henrys_sensitivity(standout_df)
    figure4_uncertainty_envelope(standout_df, uq_df)
    figure5_pareto_frontier(henrys_df, uq_df)

    logger.info(f"\nAll figures saved to {FIG_DIR}")


if __name__ == "__main__":
    main()
